# Psych 205. Grad Data Analysis
# Spring 2018.  Midterm #1.
# Prof Theunissen. GSI Connor.
# My Name:        # My grade:   /10


# We are going to use the car package
library(car)

# For this exam we will look at a new data set - the 'Vocab' data on vocabulary,
# education and sex. 

# We are focusing on whether Women have a larger vocab than Men...

# Variables in the Vocab dataset:
#     vocab:     Vocabulary test score (0 - 10)
#     education: Years of education
#     sex:       Female or Male
#     year:      Year of the survey

# Let's look at some of the data:
some(Vocab)

# Question 1 (1 pt).  What is the sample size for the ENTIRE dataset?




# Because the sample size is large, if you plot all the data points at once, the
# figure will be too busy
scatterplot(vocabulary ~ education | sex, data=Vocab)

# Instead, we are going to:
#    a. Restrict ourselves to a subset of the entire dataset
#    b. Jitter (add random noise to) the datapoints in this suset
#    c. Fit regression lines to the new datapoints

# We perform steps a and b for you below. Run the following 2 lines to generate a
# scatterplot displaying the jittered datapoints:
select = sample(nrow(Vocab),200)
scatterplot(jitter(vocabulary, factor=2) ~ jitter(education, factor=2) | sex, cex=0.5, data=Vocab, subset=select, smooth=FALSE, reg.line=FALSE)




# Question 2 (1 pt). Using the output of lm command, calculate the mean vocabulary score 
# for male and females: store these values in new variables. Looking at the summary 
# (including the R2 adj and the little "**" that I had asked you to ignore), what conclusion would you make?






# Question 3 (1 pt).  Verify your answer for the male and female means using the
# tapply command.





# Question 4 (1 pt).  Using the abline command, plot lines corresponding to the
# male and female means on the scatterplot we generated earlier (Use your answers to Q2). 
# Use a different color for each line to match the legend of the graph (Use the col= argument to
# specify the color - see R's help)


# Question 5 (0.5 pts).  Use the lm command to test for the effect of sex and
# education on test score (be sure to include the interaction term). Display the summary
# results from this new model. 






# Question 6 (1.5 pts). We are going to further examine the effect of sex on vocab. 
# Generate summary reports for these 5 models:
# 1. Model from question 2
# 2. Model from question 5
# 3. Model that predicts vocab from sex and education but witout interaction.
# 4. Model that predics education from sex.
# 5. Model that predics vocab from education.

#  Use those summaries to make conclusions on the effect of sex on vocab and try
# to explain the changes that you observe on the relevant coefficients.



# # Question 7 (1 pts). Run the following command to make a new scatterplot:
scatterplot(jitter(vocabulary, factor=2) ~ jitter(education, factor=2) | sex, cex=0.5, data=Vocab, subset=select, smooth=FALSE, reg.line=FALSE)
# Now, using abline, plot the two lines corresponding to the predicted 
# vocabulary scores as a function of education for males vs. females. Use the
# predictions generated by the model in question 5.



# Question 8 (3 pts).  Use a for loop to generate 1000 estimates for the male 
# population mean vocab score. To generate an estimate, use the "sample" command
# to samples 81 values from the male vocab scores (no replacement), and take
# their mean.Use your 1000 estimates to calculate the standard error of the
# sample mean (SEM). Compare this estimate to the SEM calculated using the
# standard deviation of our entire sample of males.  Note that since the sample size
# is not identical these will not be equal but related by something that depends on sample size.
# Use the formula for SEM to figure out what that proportionality constant should be

# Get started by making a new variable that contains the vocab scores for males
# only.

vocab.Male  <- subset(Vocab$vocabulary, Vocab$sex=='Male')




